### ISSUE TITLE
Moving to a Node-based registry

### ISSUE THREAD

**Issue by andrewosh** [binder-project/binder-registry#12]
Hey @rgbkrk @captainsafia, we're getting pretty close to completing the next version of Binder, which will use this registry! The new version will include 3 primary modules `binder-build`, `binder-registry` and `binder-deploy-kubernetes`. We ended up writing two of those, alongside several helper modules, in Node. From an API perspective having one component in Go is totally OK, but as I'm starting to integrate all the modules I'm finding that the split codebase is making it hard to do consistent logging and database management. I'm thinking of porting the work here more or less directly over to Node, but wanted to run it by everyone first! I can put it in a new repo to keep this one around as a reference.

I've been scratching my head about this one for a little while, so if you think there's a better alternative let me know. If not, I'll start doing some refactoring tonight.

**Comment by rgbkrk** [comment]
That's totally fine. Plow ahead and nuke what's here. Gave me a chance to explore and implement the spec. For the time being, I ended up using it in a fairly minor way with some tmpnb pools, didn't push much further.

Thanks for reaching out!

**Comment by andrewosh** [comment]
OK great, I'll get cracking on this then. Should have everything integrated very soon!
